### ISSUE TITLE
License ? 

### ISSUE THREAD

**Issue by mhdawson** [entrocode/NodeAlarmProxy#10]
This is a nice project and I'd like to re-use in order to pull my alarm system into my home automation projects.

I'd like to submit a pull request to add an option to disable the console output from the module when you want to limit the output to that generated by the application using it.  I need an ok from my employer to contribute to open source projects and part of that is identifying what license applies to the project.

Would it be possible to and information as to what license applies (Ideally MIT) ?  I looked both in the gihub repo and npmjs and could not find it in either place.

**Comment by entrocode** [comment]
@mhdawson There you go, hopefully that helps.  Thanks!

**Comment by mhdawson** [comment]
Wow that was fast thanks.
